apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-configmap
  namespace: lesson34
data:
  multitool-configmap.port: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lesson34-configmap
  namespace: lesson34
data:
  index.html: |
    <html>
    <body>
    WOW. It's rly w0rks!!!
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson34-deployment
  namespace: lesson34
  annotations:
    kubernetes.io/change-cause: initial-launch
spec:
  selector:
    matchLabels:
      app: lesson34-app
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lesson34-app
    spec:
      containers:
      - name: lesson34-multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: multitool-configmap
              key: multitool-configmap.port
      - name: lesson34-nginx
        image: nginx:1.19
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: lesson34-html
          mountPath: /usr/share/nginx/html
      volumes:
        - name: lesson34-html
          configMap:
            name: lesson34-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: lesson34-service
  namespace: lesson34
spec:
  selector:
    app: lesson34-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
